SELECT * FROM KAGGLE_CREDIT_CARD.PUBLIC.OUTPUT_1;

SHOW GRANTS ON ROLE PC_DBT_ROLE;
SHOW GRANTS ON TABLE KAGGLE_CREDIT_CARD.PUBLIC.OUTPUT_1;

GRANT USAGE ON DATABASE KAGGLE_CREDIT_CARD TO ROLE PC_DBT_ROLE;
GRANT USAGE ON SCHEMA KAGGLE_CREDIT_CARD.PUBLIC TO ROLE PC_DBT_ROLE;
GRANT SELECT ON TABLE KAGGLE_CREDIT_CARD.PUBLIC.OUTPUT_1 TO ROLE PC_DBT_ROLE;

DROP TABLE PC_DBT_DB.DBT_MURA.MY_FIRST_DBT_MODEL;
DROP TABLE PC_DBT_DB.DBT_MURA.MY_SECOND_DBT_MODEL;
DROP VIEW PC_DBT_DB.DBT_MURA.FIRST_QUERY;


