CREATE OR ALTER TABLE KAGGLE_CREDIT_CARD.PUBLIC.RAW (
    CUST_ID VARCHAR,
    BALANCE FLOAT,
    BALANCE_FREQUENCY FLOAT,
    PURCHASES FLOAT,
    ONEOFF_PURCHASES FLOAT,
    INSTALLMENTS_PURCHASES FLOAT,
    CASH_ADVANCE FLOAT,
    PURCHASES_FREQUENCY FLOAT,
    ONEOFFPURCHASESFREQUENCY FLOAT,
    PURCHASESINSTALLMENTSFREQUENCY FLOAT,
    CASHADVANCEFREQUENCY FLOAT,
    CASHADVANCETRX FLOAT,
    PURCHASES_TRX FLOAT,
    CREDIT_LIMIT FLOAT,
    PAYMENTS FLOAT,
    MINIMUM_PAYMENTS FLOAT,
    PRCFULLPAYMENT FLOAT,
    TENURE INT
);

COPY INTO KAGGLE_CREDIT_CARD.PUBLIC.RAW 
FROM @KAGGLE_CREDIT_CARD.PUBLIC.RAW
FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER=',' SKIP_HEADER=1)
;

SELECT * FROM KAGGLE_CREDIT_CARD.PUBLIC.RAW 
;