USE ROLE ACCOUNTADMIN;
GRANT CREATE STREAMLIT ON SCHEMA KAGGLE_CREDIT_CARD.PUBLIC TO ROLE SYSADMIN;

ALTER COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU SUSPEND;
ALTER COMPUTE POOL SYSTEM_COMPUTE_POOL_CPU SET AUTO_SUSPEND_SECS = 3600;